import { ProblemTypeFactors } from '../types';

/** Shared tier presets for industrial / AI problem types */
const STANDARD_TIERS = [
  { tier: 'Basic', multiplier: 1.0 },
  { tier: 'Standard', multiplier: 1.3 },
  { tier: 'Premium', multiplier: 1.8 },
];

const INDUSTRIAL_TIERS = [
  { tier: 'Basic', multiplier: 1.0 },
  { tier: 'Standard', multiplier: 1.4 },
  { tier: 'Premium', multiplier: 2.0 },
];

export const CORE_PROBLEM_TYPES: ProblemTypeFactors[] = [
  {
    type: 'OCR_READING',
    label: 'OCR Reading',
    description: 'Document digitization, invoice processing, handwritten text recognition',
    category: 'Document & Data',
    baseComplexityFactors: { LOW: 1.0, MEDIUM: 1.4, HIGH: 1.9, VERY_HIGH: 2.5 },
    engineeringEffortRange: { min: 40, max: 800, typical: 200 },
    cloudCostMultiplier: 1.2,
    supportTiers: STANDARD_TIERS,
    volumeUnit: 'documents/month',
    perUnitProcessingRate: 0.05,
  },
  {
    type: 'DEFECT_DETECTION',
    label: 'Defect Detection',
    description: 'Visual inspection, manufacturing defects, quality control automation',
    category: 'Vision & Quality',
    baseComplexityFactors: { LOW: 1.2, MEDIUM: 1.6, HIGH: 2.2, VERY_HIGH: 3.0 },
    engineeringEffortRange: { min: 60, max: 1200, typical: 320 },
    cloudCostMultiplier: 1.5,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'images/day',
    perUnitProcessingRate: 0.08,
  },
  {
    type: 'CAD_GENERATION',
    label: 'Architecture/CAD Generation',
    description: 'Floor plans, 3D models, technical drawings generation',
    category: 'Engineering & Design',
    baseComplexityFactors: { LOW: 1.5, MEDIUM: 2.0, HIGH: 2.8, VERY_HIGH: 3.5 },
    engineeringEffortRange: { min: 80, max: 2000, typical: 480 },
    cloudCostMultiplier: 1.8,
    supportTiers: [
      { tier: 'Basic', multiplier: 1.0 },
      { tier: 'Standard', multiplier: 1.5 },
      { tier: 'Premium', multiplier: 2.2 },
    ],
    volumeUnit: 'drawings/month',
    perUnitProcessingRate: 0.15,
  },
  {
    type: 'PATTERN_MATCHING',
    label: 'Pattern Matching',
    description: 'Anomaly detection, signal processing, image pattern recognition',
    category: 'Vision & Quality',
    baseComplexityFactors: { LOW: 1.1, MEDIUM: 1.5, HIGH: 2.0, VERY_HIGH: 2.8 },
    engineeringEffortRange: { min: 50, max: 1000, typical: 280 },
    cloudCostMultiplier: 1.3,
    supportTiers: STANDARD_TIERS,
    volumeUnit: 'signals/hour',
    perUnitProcessingRate: 0.03,
  },
];

export const INDUSTRIAL_AUTOMATION_PROBLEM_TYPES: ProblemTypeFactors[] = [
  {
    type: 'PROCESS_EFFICIENCY',
    label: 'Process Efficiency Optimization',
    description: 'OEE improvement, bottleneck detection, cycle time reduction, throughput optimization across production lines',
    category: 'Industrial Automation',
    baseComplexityFactors: { LOW: 1.3, MEDIUM: 1.7, HIGH: 2.3, VERY_HIGH: 3.1 },
    engineeringEffortRange: { min: 80, max: 1500, typical: 360 },
    cloudCostMultiplier: 1.4,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'batches/day',
    perUnitProcessingRate: 0.06,
  },
  {
    type: 'PREDICTIVE_MAINTENANCE',
    label: 'Predictive Maintenance',
    description: 'Equipment failure prediction, remaining useful life estimation, vibration and thermal anomaly detection',
    category: 'Industrial Automation',
    baseComplexityFactors: { LOW: 1.4, MEDIUM: 1.8, HIGH: 2.4, VERY_HIGH: 3.2 },
    engineeringEffortRange: { min: 100, max: 1600, typical: 400 },
    cloudCostMultiplier: 1.6,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'sensor readings/hour',
    perUnitProcessingRate: 0.02,
  },
  {
    type: 'PREDICTIVE_QUALITY',
    label: 'Predictive Quality Analytics',
    description: 'Forecast quality defects before they occur, SPC enhancement, root cause analysis from process parameters',
    category: 'Industrial Automation',
    baseComplexityFactors: { LOW: 1.3, MEDIUM: 1.7, HIGH: 2.2, VERY_HIGH: 2.9 },
    engineeringEffortRange: { min: 90, max: 1400, typical: 350 },
    cloudCostMultiplier: 1.5,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'production runs/day',
    perUnitProcessingRate: 0.07,
  },
  {
    type: 'PRODUCTION_SCHEDULING',
    label: 'Production Scheduling & Planning',
    description: 'AI-driven job scheduling, resource allocation, changeover optimization, constraint-based planning',
    category: 'Industrial Automation',
    baseComplexityFactors: { LOW: 1.5, MEDIUM: 2.0, HIGH: 2.6, VERY_HIGH: 3.4 },
    engineeringEffortRange: { min: 120, max: 1800, typical: 450 },
    cloudCostMultiplier: 1.3,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'work orders/day',
    perUnitProcessingRate: 0.04,
  },
  {
    type: 'ENERGY_OPTIMIZATION',
    label: 'Energy & Sustainability Optimization',
    description: 'Power consumption forecasting, load balancing, carbon footprint reduction, utility cost optimization',
    category: 'Industrial Automation',
    baseComplexityFactors: { LOW: 1.2, MEDIUM: 1.6, HIGH: 2.1, VERY_HIGH: 2.8 },
    engineeringEffortRange: { min: 70, max: 1200, typical: 300 },
    cloudCostMultiplier: 1.2,
    supportTiers: STANDARD_TIERS,
    volumeUnit: 'MWh/month',
    perUnitProcessingRate: 0.12,
  },
  {
    type: 'ROBOTIC_AUTOMATION',
    label: 'Robotic & Cobot Automation',
    description: 'Motion planning, grasp detection, pick-and-place optimization, human-robot collaboration safety',
    category: 'Industrial Automation',
    baseComplexityFactors: { LOW: 1.6, MEDIUM: 2.1, HIGH: 2.8, VERY_HIGH: 3.6 },
    engineeringEffortRange: { min: 150, max: 2000, typical: 520 },
    cloudCostMultiplier: 1.7,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'robots/coordinated',
    perUnitProcessingRate: 0.18,
  },
  {
    type: 'WORKER_SAFETY',
    label: 'Worker Safety Monitoring',
    description: 'PPE compliance detection, hazard zone intrusion alerts, ergonomic risk assessment, safety incident prevention',
    category: 'Industrial Automation',
    baseComplexityFactors: { LOW: 1.2, MEDIUM: 1.6, HIGH: 2.2, VERY_HIGH: 2.9 },
    engineeringEffortRange: { min: 60, max: 1000, typical: 280 },
    cloudCostMultiplier: 1.4,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'cameras/monitored',
    perUnitProcessingRate: 0.09,
  },
  {
    type: 'SUPPLY_CHAIN_FORECASTING',
    label: 'Supply Chain & Demand Forecasting',
    description: 'Demand prediction, inventory optimization, supplier risk scoring, logistics route planning',
    category: 'Industrial Automation',
    baseComplexityFactors: { LOW: 1.3, MEDIUM: 1.7, HIGH: 2.3, VERY_HIGH: 3.0 },
    engineeringEffortRange: { min: 80, max: 1400, typical: 340 },
    cloudCostMultiplier: 1.3,
    supportTiers: STANDARD_TIERS,
    volumeUnit: 'SKUs/month',
    perUnitProcessingRate: 0.05,
  },
  {
    type: 'DIGITAL_TWIN',
    label: 'Digital Twin & Simulation',
    description: 'Virtual commissioning, what-if scenario modeling, real-time plant mirroring, simulation-driven optimization',
    category: 'Industrial Automation',
    baseComplexityFactors: { LOW: 1.8, MEDIUM: 2.3, HIGH: 3.0, VERY_HIGH: 3.8 },
    engineeringEffortRange: { min: 200, max: 2000, typical: 600 },
    cloudCostMultiplier: 2.0,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'simulation runs/month',
    perUnitProcessingRate: 0.20,
  },
  {
    type: 'AGV_FLEET_MANAGEMENT',
    label: 'AGV/AMR Fleet Coordination',
    description: 'Autonomous vehicle routing, traffic management, task assignment, warehouse intralogistics optimization',
    category: 'Industrial Automation',
    baseComplexityFactors: { LOW: 1.5, MEDIUM: 2.0, HIGH: 2.6, VERY_HIGH: 3.3 },
    engineeringEffortRange: { min: 120, max: 1600, typical: 420 },
    cloudCostMultiplier: 1.5,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'vehicles/fleet',
    perUnitProcessingRate: 0.10,
  },
  {
    type: 'PROCESS_CONTROL',
    label: 'Adaptive Process Control',
    description: 'Real-time setpoint optimization, model predictive control, adaptive PID tuning, closed-loop process stabilization',
    category: 'Industrial Automation',
    baseComplexityFactors: { LOW: 1.6, MEDIUM: 2.1, HIGH: 2.8, VERY_HIGH: 3.5 },
    engineeringEffortRange: { min: 150, max: 1800, typical: 500 },
    cloudCostMultiplier: 1.4,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'control loops',
    perUnitProcessingRate: 0.14,
  },
  {
    type: 'SEMANTIC_INSPECTION',
    label: 'Semantic Visual Inspection',
    description: 'Natural language-guided inspection, multi-modal defect reasoning, complex assembly verification with vision-language models',
    category: 'Vision & Quality',
    baseComplexityFactors: { LOW: 1.5, MEDIUM: 2.0, HIGH: 2.7, VERY_HIGH: 3.5 },
    engineeringEffortRange: { min: 100, max: 1600, typical: 400 },
    cloudCostMultiplier: 1.8,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'inspections/day',
    perUnitProcessingRate: 0.11,
  },
];

export const AI_GENERAL_PROBLEM_TYPES: ProblemTypeFactors[] = [
  {
    type: 'NLP_DOCUMENT_INTELLIGENCE',
    label: 'NLP & Document Intelligence',
    description: 'Contract analysis, technical manual parsing, knowledge extraction, intelligent search over engineering documents',
    category: 'AI & Analytics',
    baseComplexityFactors: { LOW: 1.2, MEDIUM: 1.6, HIGH: 2.1, VERY_HIGH: 2.8 },
    engineeringEffortRange: { min: 60, max: 1200, typical: 300 },
    cloudCostMultiplier: 1.4,
    supportTiers: STANDARD_TIERS,
    volumeUnit: 'documents/month',
    perUnitProcessingRate: 0.06,
  },
  {
    type: 'TIME_SERIES_FORECASTING',
    label: 'Time-Series Forecasting',
    description: 'Production output forecasting, market demand curves, sensor trend prediction, seasonal pattern analysis',
    category: 'AI & Analytics',
    baseComplexityFactors: { LOW: 1.1, MEDIUM: 1.5, HIGH: 2.0, VERY_HIGH: 2.6 },
    engineeringEffortRange: { min: 50, max: 1000, typical: 260 },
    cloudCostMultiplier: 1.2,
    supportTiers: STANDARD_TIERS,
    volumeUnit: 'data points/hour',
    perUnitProcessingRate: 0.01,
  },
  {
    type: 'ANOMALY_DETECTION',
    label: 'Anomaly Detection',
    description: 'Multivariate outlier detection across PLCs, SCADA, MES data streams for early warning of process deviations',
    category: 'AI & Analytics',
    baseComplexityFactors: { LOW: 1.2, MEDIUM: 1.6, HIGH: 2.2, VERY_HIGH: 2.9 },
    engineeringEffortRange: { min: 70, max: 1200, typical: 320 },
    cloudCostMultiplier: 1.5,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'data streams',
    perUnitProcessingRate: 0.04,
  },
  {
    type: 'COMPUTER_VISION_TRACKING',
    label: 'Computer Vision Tracking',
    description: 'Object tracking on production lines, inventory counting, pallet identification, assembly step verification',
    category: 'Vision & Quality',
    baseComplexityFactors: { LOW: 1.3, MEDIUM: 1.7, HIGH: 2.3, VERY_HIGH: 3.0 },
    engineeringEffortRange: { min: 80, max: 1400, typical: 360 },
    cloudCostMultiplier: 1.6,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'video streams',
    perUnitProcessingRate: 0.09,
  },
  {
    type: 'GENERATIVE_DESIGN',
    label: 'Generative Design',
    description: 'AI-assisted part design, topology optimization, material selection, design-to-manufacturing automation',
    category: 'Engineering & Design',
    baseComplexityFactors: { LOW: 1.6, MEDIUM: 2.2, HIGH: 2.9, VERY_HIGH: 3.7 },
    engineeringEffortRange: { min: 120, max: 2000, typical: 500 },
    cloudCostMultiplier: 1.9,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'design iterations/month',
    perUnitProcessingRate: 0.16,
  },
  {
    type: 'EDGE_AI_DEPLOYMENT',
    label: 'Edge AI Deployment',
    description: 'On-device inference, model compression, edge-gateway orchestration for low-latency factory-floor AI',
    category: 'AI & Analytics',
    baseComplexityFactors: { LOW: 1.4, MEDIUM: 1.9, HIGH: 2.5, VERY_HIGH: 3.3 },
    engineeringEffortRange: { min: 100, max: 1600, typical: 420 },
    cloudCostMultiplier: 1.1,
    supportTiers: INDUSTRIAL_TIERS,
    volumeUnit: 'edge devices',
    perUnitProcessingRate: 0.13,
  },
];

export const ALL_DEFAULT_PROBLEM_TYPES: ProblemTypeFactors[] = [
  ...CORE_PROBLEM_TYPES,
  ...INDUSTRIAL_AUTOMATION_PROBLEM_TYPES,
  ...AI_GENERAL_PROBLEM_TYPES,
];

export const VOLUME_UNITS = [
  'documents/month',
  'images/day',
  'requests/second',
  'drawings/month',
  'signals/hour',
  'batches/day',
  'sensor readings/hour',
  'production runs/day',
  'work orders/day',
  'MWh/month',
  'robots/coordinated',
  'cameras/monitored',
  'SKUs/month',
  'simulation runs/month',
  'vehicles/fleet',
  'control loops',
  'inspections/day',
  'data points/hour',
  'data streams',
  'video streams',
  'design iterations/month',
  'edge devices',
] as const;

export type VolumeUnit = (typeof VOLUME_UNITS)[number];
